#lines!
lo_v <- loess(V ~ depth, xrf,model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.25)
lo_ni <- loess(Ni ~ depth, xrf,model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.25)
lo_zn_ti <- loess(Zn/Ti ~ depth, xrf,model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.25)
lo_cu_ti <- loess(Cu/Ti ~ depth, xrf,model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.25)
lo_ni_ti <- loess(Ni/Ti ~ depth, xrf,model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.25)
lo_zn <- loess(Zn ~ depth, xrf,model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.25)
lo_cu <- loess(Cu ~ depth, xrf,model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.25)
lo_ti <- loess(Ti ~ depth, xrf,model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.25)
lo_cr <- loess(Cr ~ depth, xrf,model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.25)
lo_cr_ti <- loess(Cr/Ti ~ depth, xrf,model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.25)
lo_ti <- loess(Ti ~ depth, xrf,model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.25)
lo_mn <- loess(Mn ~ depth, xrf,model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.25)
lo_fe <- loess(Fe ~ depth, xrf,model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.25)


age_lo_v <- loess(xrf$V[1:81] ~ agemodel_all$date, model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.1)
age_lo_ni <- loess(xrf$Ni[1:81] ~ agemodel_all$date, model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.1)
age_lo_zn_ti <- loess(xrf$Zn[1:81]/xrf$Ti[1:81] ~ agemodel_all$date, model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.1)
age_lo_cu_ti <- loess(xrf$Cu[1:81]/xrf$Ti[1:81] ~ agemodel_all$date, model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.1)
age_lo_ni_ti <- loess(xrf$Ni[1:81]/xrf$Ti[1:81] ~ agemodel_all$date, model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.1)
age_lo_zn <- loess(xrf$Zn[1:81] ~ agemodel_all$date, model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.1)
age_lo_cu <- loess(xrf$Cu[1:81] ~ agemodel_all$date, model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.1)
age_lo_ti <- loess(xrf$Ti[1:81] ~ agemodel_all$date, model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.1)
age_lo_cr <- loess(xrf$Cr[1:81] ~ agemodel_all$date, model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.1)
age_lo_cr_ti <- loess(xrf$Cr[1:81]/xrf$Ti[1:81] ~ agemodel_all$date, model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.1)
age_lo_ti <- loess(xrf$Ti[1:81] ~ agemodel_all$date, model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.1)
age_lo_mn <- loess(xrf$Mn[1:81] ~ agemodel_all$date, model = FALSE, degree = 2,parametric = FALSE,family = "gaussian", span=0.1)
