library(rstudioapi)

floodYear1 <- 1964
floodDepth1 <- approx(agemodel_coo6$date, agemodel_coo6$depth, floodYear)

floodYear2 <- 1887
floodDepth2 <- approx(agemodel_coo6$date, agemodel_coo6$depth, floodYear)

op <- par(mfrow = c(1,10))
par(mar = c(5,1,4,1))
plot(xrf$Ti, xrf$core_depth, type = "n", xlab="", axes = FALSE, ylab="", ylim=c(180,0),xlim=c(0,650))

plot(xrf$Ti, xrf$core_depth, xlab="Ti", ylab="Depth (cm)", ylim=c(180,0),xlim=c(0,650))
lines(predict(lo_Ti), xrf$core_depth, lwd=2)
abline(h=78, col='red', lty=2)
abline(h=78, col='red', lty=2)
mtext(side = 2, line = 3, "Depth (cm)", cex= .75)

plot(xrf$Al, xrf$core_depth, xlab="Al", ylab="", yaxt = 'n', ylim=c(180,0))
lines(predict(lo_Al), xrf$core_depth, lwd=2)
abline(h=78, col='red', lty=2)
abline(h=floodYear1, col='grey40', lty=2, lwd=1.5)
abline(h=floodYear2, col='grey40', lty=2, lwd=1.5)

plot(xrf$Mn, xrf$core_depth, xlab="Mn",ylab=" ", yaxt = 'n',ylim=c(180,0))
lines(predict(lo_mn), xrf$core_depth, lwd=2)
abline(h=78, col='red', lty=2)
abline(h=floodYear1, col='grey40', lty=2, lwd=1.5)
abline(h=floodYear2, col='grey40', lty=2, lwd=1.5)
plot(xrf$Zn, xrf$core_depth, xlab="Zn",ylab=" ", yaxt = 'n',ylim=c(180,0))
lines(predict(lo_zn), xrf$core_depth, lwd=2)
abline(h=78, col='red', lty=2)
abline(h=floodYear1, col='grey40', lty=2, lwd=1.5)
abline(h=floodYear2, col='grey40', lty=2, lwd=1.5)
plot(xrf$Zn/xrf$Ti,xrf$core_depth,   xlab="Zn/Ti", yaxt = 'n',ylab=" ",ylim=c(180,0), xlim=c(0,20))
lines(predict(lo_zn_ti), xrf$core_depth, lwd=2)
abline(h=78, col='red', lty=2)
abline(h=floodYear1, col='grey40', lty=2, lwd=1.5)
abline(h=floodYear2, col='grey40', lty=2, lwd=1.5)
plot(xrf$Zn/xrf$Al, xrf$core_depth, xlab="Zn/Al", yaxt = 'n',ylab=" ", ylim=c(180,0),xlim=c(0,20))
lines(predict(lo_zn_al), xrf$core_depth, lwd=2)
abline(h=78, col='red', lty=2)
abline(h=floodYear1, col='grey40', lty=2, lwd=1.5)
abline(h=floodYear2, col='grey40', lty=2, lwd=1.5)
plot(xrf$Ni, xrf$core_depth, xlab="Ni",ylab=" ", yaxt = 'n',ylim=c(180,0))
lines(predict(lo_ni), xrf$core_depth, lwd=2)
abline(h=78, col='red', lty=2)
abline(h=floodYear1, col='grey40', lty=2, lwd=1.5)
abline(h=floodYear2, col='grey40', lty=2, lwd=1.5)
plot(xrf$Ni/xrf$Ti,xrf$core_depth,   xlab="Ni/Ti", yaxt = 'n',ylab=" ",ylim=c(180,0), xlim=c(0,20))
lines(predict(lo_ni_ti), xrf$core_depth, lwd=2)
abline(h=78, col='red', lty=2)
abline(h=floodYear1, col='grey40', lty=2, lwd=1.5)
abline(h=floodYear2, col='grey40', lty=2, lwd=1.5)
plot(xrf$Ni/xrf$Al, xrf$core_depth, xlab="Ni/Al", ylab=" ", yaxt = 'n',ylim=c(180,0),xlim=c(0,20))
lines(predict(lo_ni_al), xrf$core_depth, lwd=2)
abline(h=78, col='red', lty=2)
abline(h=floodYear1, col='grey40', lty=2, lwd=1.5)
abline(h=floodYear2, col='grey40', lty=2, lwd=1.5)
par(old.par)

#save the plot
savePlotAsImage(file = 'FinalFigure3', format = "svg", width = 1100, height = 700)

